### ISSUE TITLE
Can't connect after Ring password change

### ISSUE THREAD

**Issue by n0tf0und** [damooooooooooh/ring-adapter#6]
My Ring add-on stopped reporting motion in my Raspberry Pi (fully updated Buster) gateway.
In the past refreshing the config fixed this.
I clicked + on the gateway web page and two new Ring cameras (recently installed) were added to my existing ring doorbell.
I only use motion from doorbell to trigger an action
I changed my ring password (2fa) at ring to eLFqVgmi5M2#RNzziOyU (not used now)
Previously it had been a simple alpha numeric with 2fa.
Now Ring devices do not show or connect.
I removed the ring add-on and reinstalled it
Configured with user name & new password and 2fa
At ring/authorized client devices gateway was listed before as android device now says ‘Device name not found’
Settings/developer/internal logs show
2021-07-29 08:13:31.626 INFO   : Unloading RingAdapter
2021-07-29 08:13:37.541 INFO   : Loading add-on: ring-adapter
2021-07-29 08:13:39.362 INFO   : ring-adapter: Opening database: /home/pi/.webthings/config/db.sqlite3
2021-07-29 08:13:39.413 INFO   : ring-adapter: Ignoring https://raw.githubusercontent.com/WebThingsIO/gateway-addon-ipc-schema/master/schema.json because it has no messageType
2021-07-29 08:13:41.007 INFO   : ring-adapter: Ignoring https://raw.githubusercontent.com/WebThingsIO/gateway-addon-ipc-schema/master/messages/definitions.json because it has no messageType
2021-07-29 08:13:43.678 INFO   : ring-adapter: Loading add-on ring-adapter from /home/pi/.webthings/addons/ring-adapter
2021-07-29 08:13:46.459 INFO   : ring-adapter: Attempting authentication with 2fa otp
2021-07-29 08:13:47.256 INFO   : ring-adapter: Refresh Token updated and saved
2021-07-29 08:13:47.259 INFO   : ring-adapter: Saving config
2021-07-29 08:13:47.269 INFO   : ring-adapter: Fetching Ring devices for account myemail@server.com (not real email)
2021-07-29 08:13:47.372 INFO   : ring-adapter: Refresh Token updated and saved
2021-07-29 08:13:47.375 INFO   : ring-adapter: Saving config
2021-07-29 08:13:47.667 INFO   : ring-adapter: Unhandled Rejection
2021-07-29 08:13:47.671 ERROR  : ring-adapter: { HTTPError: Response code 404 (Not Found)
2021-07-29 08:13:47.672 ERROR  : ring-adapter:     at onResponse (/home/pi/.webthings/addons/ring-adapter/node_modules/got/dist/source/as-promise/index.js:142:28)
2021-07-29 08:13:47.673 ERROR  : ring-adapter:     at process._tickCallback (internal/process/next_tick.js:68:7)
2021-07-29 08:13:47.675 ERROR  : ring-adapter:   name: 'HTTPError',
2021-07-29 08:13:47.676 ERROR  : ring-adapter:   code: undefined,
2021-07-29 08:13:47.677 ERROR  : ring-adapter:   timings:
2021-07-29 08:13:47.678 ERROR  : ring-adapter:    { start: 1627560827507,
2021-07-29 08:13:47.680 ERROR  : ring-adapter:      socket: 1627560827626,
2021-07-29 08:13:47.681 ERROR  : ring-adapter:      lookup: 1627560827626,
2021-07-29 08:13:47.682 ERROR  : ring-adapter:      connect: 1627560827626,
2021-07-29 08:13:47.683 ERROR  : ring-adapter:      secureConnect: 1627560827626,
2021-07-29 08:13:47.684 ERROR  : ring-adapter:      upload: 1627560827626,
2021-07-29 08:13:47.686 ERROR  : ring-adapter:      response: 1627560827659,
2021-07-29 08:13:47.687 ERROR  : ring-adapter:      end: 1627560827662,
2021-07-29 08:13:47.688 ERROR  : ring-adapter:      error: undefined,
2021-07-29 08:13:47.689 ERROR  : ring-adapter:      abort: undefined,
2021-07-29 08:13:47.691 ERROR  : ring-adapter:      phases:
2021-07-29 08:13:47.692 ERROR  : ring-adapter:       { wait: 119,
2021-07-29 08:13:47.693 ERROR  : ring-adapter:         dns: 0,
2021-07-29 08:13:47.694 ERROR  : ring-adapter:         tcp: 0,
2021-07-29 08:13:47.695 ERROR  : ring-adapter:         tls: 0,
2021-07-29 08:13:47.696 ERROR  : ring-adapter:         request: NaN,
2021-07-29 08:13:47.698 ERROR  : ring-adapter:         firstByte: 33,
2021-07-29 08:13:47.699 ERROR  : ring-adapter:         download: 3,
2021-07-29 08:13:47.700 ERROR  : ring-adapter:         total: 155 } } }

Did I corrupt the token with the new password?
Any suggestions on a fix?

Thanks

**Comment by damooooooooooh** [comment]
Hi, what devices do you have?

**Comment by n0tf0und** [comment]
Ring Video Doorbell Pro - was taking motion from this for about 4 months
Ring Indoor cam (new install)
Ring stick up cam plug-in (3rd Gen) (new install)
All the new installs showed up when I hit rescan. all were inactive due to the ring addon not connecting.
I deleted them all while troubleshooting. They do not show now.
Hue add-on
Hue bridge (latest version)
5 hue lamps connected to bridge.
Date Time adaptor add-on
Timer add-on
Power Settings add-on

**Comment by n0tf0und** [comment]
ring add-on is 0.0.7

**Comment by damooooooooooh** [comment]
Ok, I've replicated the error.  Let me check.

**Comment by damooooooooooh** [comment]
3412e58 Fixes this issue, please download v0.0.8 and reconfigure with OTP.

**Comment by n0tf0und** [comment]
Works like a charm
Thanks for the quick response.
I write in PHP & Python but not JS
What was the fix???
And Thank You

**Comment by damooooooooooh** [comment]
ring changed something at the api.
